echo "      ${ORANGE}/\ ${NC}"
        echo "    ${ORANGE}_/./ ${NC}"
        echo "${ORANGE} ,-${RED}'    {$ORANGE}\`${RED}-:..${ORANGE}-'/ ${NC}"
        echo "${ORANGE}: ${GREEN}o ${RED})      _  ${ORANGE}("
        echo "${ORANGE}\"\`-..${RED}..,${ORANGE}--${RED}; \`${ORANGE}-.\ "
        echo "${ORANGE}    \`${RED}'\""
